#!/bin/bash

hostname=$1
[ "$hostname" == "" ] && echo -n "Enter hostname: " && read hostname
IP=`ip address | grep inet | grep -v inet6 | grep -v 127.0.0.1 | cut -d" " -f6 | cut -d/ -f1`

[ "$hostname" == "" ] && echo "No hostname provided." && exit 0

hostnamectl set-hostname $hostname.teleflora.com
sed -i "/$IP/d" /etc/hosts 
sed -i "/\:\:/d" /etc/hosts 
echo "$IP          $hostname $hostname.teleflora.com">>/etc/hosts

exit 0
