#!/bin/bash

find . -name "*.md5" -exec rm {} \;
for file in `find . -type f | grep -v hash_files | grep -v README`
do
MD5="`md5sum $file | cut -d' ' -f1`"
echo $MD5 >$file.md5
done
rm ./rh*/stage/*.md5
