#!/bin/bash

VERSION="1.17.6"
BACKEND="http://rhel8repo.centralus.cloudapp.azure.com/ostools-1.17"
CMDLINEVARS="`echo $@ | cut -d" " -f2-`"

ID=$(/usr/bin/id -u)
[ $ID -ne 0 ] && echo "You must be root to run $0." && exit 1
[ "`grep ' release 7.' /etc/redhat-release`" != "" ] && GROUP="rh7"
[ "`grep ' release 8.' /etc/redhat-release`" != "" ] && GROUP="rh8"
[ "`grep ' release 9.' /etc/redhat-release`" != "" ] && GROUP="rh9"
SCRIPT="$1"
SUBGROUP="$1"
n="${15:-20}"
[ ! -d /usr/bin/.updateos ] &&  mkdir /usr/bin/.updateos

usage() {
SUBGROUP=""
rm -f /usr/bin/.updateos/*
echo "updateos - $VERSION - USAGE: sudo updateos (groupname|scriptname)"
  echo ""
  echo "$GROUP"
  for SCRIPT in `/usr/bin/curl -ls $BACKEND/$GROUP/ | sed 's/<a\ href=/~/g'  | grep -v colspan | cut -d~ -f2 | cut -d\" -f2 | grep -v \< | grep -v \/\/ | grep -v \? | grep -v ^/ | grep -v \/ | grep -v .md5 | grep -v nopub`
    do
    [ ! -f /usr/bin/.updateos/$SCRIPT ] && touch /usr/bin/.updateos/$SCRIPT
      [ "`curl -s $BACKEND/$GROUP/$SCRIPT.md5`" != "`md5sum /usr/bin/.updateos/$SCRIPT | cut -d" " -f1`" ] && download_script
    DESC="`grep ^#DESC /usr/bin/.updateos/$SCRIPT | sed -e 's/^#DESC\ //g'`"
    SCRIPT="$SCRIPT$(printf '%*s' "$n" "")"        
    var="$(echo "${SCRIPT}"|grep -Eo "^.{1,$n}")" 
    echo -n " "
    printf '%s' "${var}" 
    echo ${DESC:0:58}
    done
  for SUBGROUP in `/usr/bin/curl -ls $BACKEND/$GROUP/ | sed 's/<a\ href=/~/g'  | grep -v colspan | cut -d~ -f2 | cut -d\" -f2 | grep -v \< | grep -v \/\/ | grep -v \? | grep -v ^/ | grep \/ | grep -v .md5 | grep -v nopub`
    do
    echo " $SUBGROUP"
    done
exit 1
}

run_subgroup() {
for SCRIPT in `/usr/bin/curl -ls $BACKEND/$GROUP/$SUBGROUP/ | grep -v $SUBGROUP | sed 's/<a\ href=/~/g'  | grep -v colspan | cut -d~ -f2 | cut -d\" -f2 | grep -v \< | grep -v \/\/ | grep -v \? | grep -v ^/ | grep -v \/ | grep -v .md5 | grep -v nopub`
  do
  echo "----> `date` - Running $GROUP $SUBGROUP $SCRIPT..." | tee -a /tmp/updateos.log
  [ ! -f /usr/bin/.updateos/$SCRIPT ] && touch /usr/bin/.updateos/$SCRIPT
    [ "`curl -s $BACKEND/$GROUP/$SCRIPT.md5`" != "`md5sum /usr/bin/.updateos/$SCRIPT | cut -d" " -f1`" ] && download_script
  /usr/bin/.updateos/${SCRIPT} 2>&1 | tee -a /tmp/updateos.log
  EXIT="${PIPESTATUS[0]}"
  [ "$EXIT" != "0" ] && echo "Failed." | tee -a /tmp/updateos.log && echo "" && exit $EXIT
  echo "----> `date` - Success." | tee -a /tmp/updateos.log
  echo "" | tee -a /tmp/updateos.log
  done
exit $EXIT
}

run_script() {
SUBGROUP=""
echo "----> `date` -  Running $SCRIPT ..." | tee -a /tmp/updateos.log
[ ! -f /usr/bin/.updateos/$SCRIPT ] && touch /usr/bin/.updateos/$SCRIPT
  [ "`curl -s $BACKEND/$GROUP/$SCRIPT.md5`" != "`md5sum /usr/bin/.updateos/$SCRIPT | cut -d" " -f1`" ] && download_script
[ "`echo $2 | grep -i help`" != "" ] && script_help
/usr/bin/.updateos/${SCRIPT} $CMDLINEVARS 2>&1 | tee -a /tmp/updateos.log
EXIT="${PIPESTATUS[0]}"
[ "$EXIT" != "0" ] && echo "Failed." | tee -a /tmp/updateos.log && echo "" && exit $EXIT
echo "----> `date` - Success." | tee -a /tmp/updateos.log
echo "" | tee -a /tmp/updateos.log
exit $EXIT
}

script_help() {
for line in `grep ^#HELP $SCRIPT`
  do
  echo "$SCRIPT Help     -"
  echo "------------------" 
  echo "`echo $line | cut -d" " -f2-`" 
  done
exit 0
}

download_script () {
[ "`curl -s $BACKEND/ | grep updateos`" == "" ] && echo "Backend not reachable. Using local copy." && return 0 
rm -f /usr/bin/.updateos/$SCRIPT
/usr/bin/curl -s $BACKEND/$GROUP/$SUBGROUP/$SCRIPT -o /usr/bin/.updateos/$SCRIPT
chmod +x /usr/bin/.updateos/${SCRIPT}
}

# main
[ "$#" == "0" ] || [ "`echo $1 | grep help 2>/dev/null`" != "" ] && usage
for file in `/usr/bin/curl -ls $BACKEND/$GROUP/ | sed 's/<a\ href=/~/g'  | grep -v colspan | cut -d~ -f2 | cut -d\" -f2 | grep -v \< | grep -v \/\/ | grep -v \? | grep -v ^/ | grep $SCRIPT | grep -v .md5 | grep -v nopub`
  do
  [ "`echo $file | grep \/`" != "" ] && run_subgroup
  [ "`echo $file | grep -v \/`" != "" ] && run_script
  done
echo "updateos - $VERSION - USAGE: sudo updateos (groupname|scriptname)"
exit 1
