#!/bin/bash

#DESC CentOS yum repo file install.

# verify root
ID=`/usr/bin/id -u`
[ $ID -ne 0 ] && echo "You must be root to run $0." && exit 1

# disable and remove subscription manager if there.
[ -f /etc/yum/pluginconf.d/subscription-manager ] && sed -i 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/subscription-manager.conf
yum -y remove subscription-manager

# move off redhat.repo if there.
[ -f /etc/yum.repos.d/redhat.repo ] && mv /etc/yum.repos.d/redhat.repo ~

# create centos repos file
cat > /etc/yum.repos.d/centosrepos.repo <<EOF
[base]
name=CentOS $releasever – Base
baseurl=http://mirror.centos.org/centos/7/os/$basearch/
gpgcheck=0
enabled=1

[updates]
name=CentOS $releasever – Updates
baseurl=http://mirror.centos.org/centos/7/updates/$basearch/
gpgcheck=0
enabled=1

[extras]
name=CentOS $releasever – Extras
baseurl=http://mirror.centos.org/centos/7/extras/$basearch/
gpgcheck=0
enabled=1
EOF
[ $? -ne 0 ] && echo "Could not create centosrepo file." && exit 3

# update system
yum -y update
[ $? -ne 0 ] && echo "Could not install updates." && exit 4

exit 0
