#!/bin/bash

#DESC Creates folders need by the POS installation.
[ ! -d /usr2 ] && mkdir /usr2
[ ! -d /usr2/bbx ] && mkdir /usr2/bbx
[ ! -d /usr2/bbx/bin ] && mkdir /usr2/bbx/bin
[ ! -d /usr2/bbx/log ] && mkdir /usr2/bbx/log
[ ! -d /usr2/bbx/config ] && mkdir /usr2/bbx/config
[ ! -d /usr/java ] && mkdir /usr/java
exit 0
