#!/bin/bash

#DESC Harden the system per PCI/PADSS guidelines.

/usr2/ostools/bin/harden_linux.pl --ssh
/usr2/ostools/bin/harden_linux.pl --hostsallow
/usr2/ostools/bin/harden_linux.pl --services
/usr2/ostools/bin/harden_linux.pl --logging
/usr2/ostools/bin/harden_linux.pl --logrotate
/usr2/ostools/bin/harden_linux.pl --sudo

/usr2/ostools/bin/updateos.pl --samba
/usr2/ostools/bin/updateos.pl --cupsconf
/usr2/ostools/bin/updateos.pl --samba-gen-conf
/usr2/ostools/bin/updateos.pl --samba-set-passdb
/usr2/ostools/bin/updateos.pl --audit-system-configure
/usr2/ostools/bin/updateos.pl --motd
/usr2/ostools/bin/harden_linux.pl --ids
/usr2/ostools/bin/harden_linux.pl --pam
/usr2/ostools/bin/updateos.pl --configure-grub2
/usr2/ostools/bin/updateos.pl --default-password-hash

systemctl restart sshd
systemctl restart rsyslog
systemctl restart smb
systemctl restart cups

systemctl enable upsd
systemctl enable chrony
systemctl enable smb
systemctl enable cups

