#!/bin/bash

cd /tmp
[ ! -f ./apcupsd-3.14.14-18.el8.x86_64.rpm ] && wget http://rhel8repo.centralus.cloudapp.azure.com/support/apcupsd-3.14.14-18.el8.x86_64.rpm
yum -y localinstall ./apcupsd-3.14.14-18.el8.x86_64.rpm
/usr2/ostools/bin/updateos.pl --ups
