#!/bin/bash

#DESC Inplace OS upgrade from RH7 to RH8 - RTI.

echo "---> Upgrading OS to RHEL8 ..." | tee -a /tmp/updateos.log
echo "" | tee -a /tmp/updateos.log

# add rh7 extras repo.
cat > /etc/yum.repos.d/tfrhel7extras.repo << EOF
[RH7extras]
name=RH7extras
baseurl=https://tfrhelrepo.centralus.cloudapp.azure.com/rhel-7-server-extras-rpms
enabled=1
gpgcheck=0
EOF

# add leapp package
yum -y install leapp-upgrade-el7toel8

# add leapp repos
cat > /etc/leapp/files/leapp_upgrade_repositories.repo << EOF
[RH8AppStream]
name=RH8AppStream
baseurl=http://rhel8repo.centralus.cloudapp.azure.com/rhel-8-for-x86_64-appstream-rpms

[RH8BaseOS]
name=RH8BaseOS
baseurl=http://rhel8repo.centralus.cloudapp.azure.com/rhel-8-for-x86_64-baseos-rpms

EOF

#download leapp metadata
cd /etc/leapp/files
wget http://rhel8repo.centralus.cloudapp.azure.com/support/leapp-data-22.tar.gz
tar xvfz ./leapp-data-22.tar.gz

#remove unneeded kernel drivers
modprobe --remove -v btrfs
rmmod btrfs
rmmod xor
rmmod raid6_pq
echo "blacklist btrfs" >> /etc/modprobe.d/btrfs-blacklist.conf
echo "install btrfs /bin/false" >> /etc/modprobe.d/btrfs-blacklist.conf
dracut --omit-drivers btrfs -f
#mv /lib/dracut/modules.d/90btrfs/ /tmp
sed -i '/^GRUB_CMDLINE_LINUX=/s/"$/ <module_name>.blacklist=1 rd.driver.blacklist=<module_name>"/' /etc/sysconfig/grub
grub2-mkconfig -o /boot/grub2/grub.cfg 
grub2-mkconfig -o /boot/efi/EFI/redhat/grub.cfg 

#create leapp answer file
cat > /var/log/leapp/answerfile << EOF
[remove_pam_pkcs11_module_check]
# Title:              None
# Reason:             Confirmation
# =================== remove_pam_pkcs11_module_check.confirm ==================
# Label:              Disable pam_pkcs11 module in PAM configuration? If no, the upgrade process will be interrupted.
# Description:        PAM module pam_pkcs11 is no longer available in RHEL-8 since it was replaced by SSSD.
# Reason:             Leaving this module in PAM configuration may lock out the system.
# Type:               bool
# Default:            None
# Available choices: True/False
# Unanswered question. Uncomment the following line with your answer
confirm = True
EOF

#add script to run after reboot.
updateos post_install

#remove rh8 unsupported pam.d modules.
sed -i '/pam_tally2/d' /etc/pam.d/*
sed -i '/pam_pkcs11/d' /etc/pam.d/*

#remove sendmail reference in hosts.allow.
sed -i '/sendmail/d' /etc/hosts.allow

#remove tcp_wrappers no longer supported.
yum -y remove tcp_wrappers
[ -f /etc/hosts.allow ] && mv -f /etc/hosts.allow /tmp
[ -f /etc/hosts.deny ] && mv -f /etc/hosts.deny /tmp

#remove vsftpd.
yum -y remove vsftpd

#change nic naming
systemctl start NetworkManager
updateos change_nics
updateos install_ostools-1.16

# run leap upgrade
leapp upgrade --target 8.6 --no-rhsm --reboot
