#!/bin/bash

#DESC Inplace OS upgrade from RH7 to RH8 - RTI.

echo "---> Upgrading RHEL7 to RHEL8 ..." | tee -a /tmp/updateos.log
echo "" | tee -a /tmp/updateos.log

# add rh7 extras repo.
cat > /etc/yum.repos.d/tfrhel7extras.repo << EOF
[RH7extras]
name=RH7extras
baseurl=https://tfrhelrepo.centralus.cloudapp.azure.com/rhel-7-server-extras-rpms
enabled=1
EOF

# add leapp package
yum -y install leapp-upgrade

# add leapp repos
cat > /etc/leapp/files/leapp_upgrade_repositories.repo << EOF
[RH8AppStream]
name=RH8AppStream
baseurl=http://rhel8repo.centralus.cloudapp.azure.com/rhel-8-for-x86_64-appstream-rpms

[RH8BaseOS]
name=RH8BaseOS
baseurl=http://rhel8repo.centralus.cloudapp.azure.com/rhel-8-for-x86_64-baseos-rpms

EOF

#download leapp metadata
cd /etc/leapp/files
wget http://rhel8repo.centralus.cloudapp.azure.com/support/leapp-data17.tar.gz
tar xvfz ./leapp-data17.tar.gz

#remove unneeded kernel drivers
modprobe -r pata_acpi

#create leapp answer file
cat > /var/log/leapp/answerfile << EOF
[remove_pam_pkcs11_module_check]
# Title:              None
# Reason:             Confirmation
# =================== remove_pam_pkcs11_module_check.confirm ==================
# Label:              Disable pam_pkcs11 module in PAM configuration? If no, the upgrade process will be interrupted.
# Description:        PAM module pam_pkcs11 is no longer available in RHEL-8 since it was replaced by SSSD.
# Reason:             Leaving this module in PAM configuration may lock out the system.
# Type:               bool
# Default:            None
# Available choices: True/False
# Unanswered question. Uncomment the following line with your answer
confirm = True
EOF

#add script to run after reboot.
#updateos rh7 post_install

#remove pam_tally2 support from pam.d. rh8 doesn't support.
sed -i '/pam_tally2/d' /etc/pam.d/system-auth-teleflora

# run leap upgrade
leapp upgrade --target 8.6 --no-rhsm --reboot
