#!/bin/bash

#DESC Check for btrfs and/or pata_acpi kern mods and remove if present.
#btrfs
if [ "`lsmod | grep btrfs`" != "" ]
then
modprobe -r btrfs
rmmod btrfs
echo "blacklist btrfs" >> /etc/modprobe.d/btrfs-blacklist.conf
echo "install btrfs /bin/false" >> /etc/modprobe.d/btrfs-blacklist.conf
[ ! -d /etc/dracut.conf.d ] && mkdir -p /etc/dracut.conf.d
echo omit_drivers+=\" btrfs \" > /etc/dracut.conf.d/btrfs-blacklist.conf
dracut -f
grub2-mkconfig -o /boot/grub2/grub.cfg
grub2-mkconfig -o /boot/efi/EFI/redhat/grub.cfg
echo "Removed btrfs......reboot required." | tee -a /tmp/updateos.log
fi
#pata_acpi
if [ "`lsmod | grep pata_acpi`" != "" ]
then
modprobe -r pata_acpi
rmmod pata_acpi
echo "blacklist pata_acpi" >> /etc/modprobe.d/pata_acpi-blacklist.conf
echo "install pata_acpi /bin/false" >> /etc/modprobe.d/pata_acpi-blacklist.conf
[ ! -d /etc/dracut.conf.d ] && mkdir -p /etc/dracut.conf.d
echo omit_drivers+=\" pata_acpi \" > /etc/dracut.conf.d/pata_acpi-blacklist.conf
dracut -f
grub2-mkconfig -o /boot/grub2/grub.cfg
grub2-mkconfig -o /boot/efi/EFI/redhat/grub.cfg
echo "Removed psta_acpi......reboot required." | tee -a /tmp/updateos.log
fi
