#!/bin/bash

#add a 30sec sleep before starting rti.
[ "`grep sleep /etc/rc.d/init.d/rti`" == "" ] && sed -i 's/\$RTI_DIR\/bin\/startbbx/sleep\ 30\ \;\ \$RTI_DIR\/bin\/startbbx/g' /etc/rc.d/init.d/rti
