#!/bin/bash

#DESC Clone an RTI server.

# This allows you to clone from an RTI server to a new (freshly purchased physical or virtual) server that is staged and on a reachable local network.

# - Primary info
# - Users
# - Timezone
# - Hostnames
# - Printers and file shares (samba)
# - Firewall rules (iptables)
# - Mail setup (sendmail)
# - Java (/usr/java)
# - RTI (/usr2)
# - Management tools (Kaseya, Cortex, Insights)
# - Scheduled processes (cron)
# - System services (systemd, init.d)
# - TCC Install
# - Switch from primary?

# Main

