#!/usr/bin/expect
spawn smbpasswd -a tfsupport 
expect "New SMB password:" { send "T3l3fl0r4#\r" }
expect "Retype new SMB password:" { send "T3l3fl0r4#\r" }
interact

#!/usr/bin/expect
spawn smbpasswd -a rti
expect "New SMB password:" { send "rti\r" }
expect "Retype new SMB password:" { send "rti\r" }
interact

#!/usr/bin/expect
spawn smbpasswd -a odbc
expect "New SMB password:" { send "odbc99\r" }
expect "Retype new SMB password:" { send "odbc99\r" }
interact

#DESC Set samba passwords for app users.
