#!/bin/bash

#DESC Copy RTI from another server. (Must have root ssh enabled.)

# Install required packages.
yum install -y glib2 fuse3-libs
yum install -y http://rhel8repo.centralus.cloudapp.azure.com/support/fuse-sshfs-2.8-7.el8.x86_64.rpm
[ ! -d /SOURCE ] && mkdir /SOURCE

echo -n "Source IP: " && read SOURCE
ping -c 1 $SOURCE
[ "$?" != "0" ] && echo "Can't see server." && exit 1
sshfs root@$SOURCE:/ /SOURCE
[ "$?" != "0" ] && echo "Can't access server." && exit 2

echo Stopping rti...
systemctl stop rti bbj blm cups smb iptables
echo

echo Copying data from...
echo $SOURCE
rsync -avhz --exclude '*.log' --exclude 'tcc*' --exclude 'basis-old' --exclude '*backups*' --exclude 'basis.lic' --exclude '*ostools*' /SOURCE/usr2 / && chown -R tfsupport:rti /usr2 
rsync -avhz /SOURCE/etc/samba /samba && chown -R root:root /etc/samba
rsync -avhz /SOURCE/etc/cups /cups && chown -R root:root /etc/cups
rsync -avhz /SOURCE/etc/mail /mail && chown -R root:root /etc/mail
rsync -avhz /SOURCE/home / && chown -R tfsupport /home/tfsupport
rsync -avhz /SOURCE/usr/java / && chown -R root:root /usr/java
cp -f /$SOURCE/etc/passwd /etc/passwd && chown root:root /etc/passwd
cp -f /$SOURCE/etc/shadow /etc/shadow && chown root:root /etc/shadow
cp -f /$SOURCE/etc/group /etc/group && chown root:root /etc/group
cp -f /$SOURCE/etc/sudoers /etc/sudoers && chown root:root /etc/sudoers
cp -f /$SOURCE/etc/sysconfig/iptables /etc/sysconfig/iptables && chown root:root /etc/sysconfig/iptables
echo
umount /SOURCE
[ "$?" != "0" ] && echo "Can't umount source."

echo Installing and disabling RTI realtime...
updateos install_tcc
updateos realtime_disable
echo

echo Starting systemd services...
systemctl start blm bbj rti cups smb iptables
echo

exit 0
