#!/bin/bash

#DESC Add configuration for supporting RTI install.

#Setup tfsupport ssh keys.
cd /tmp
[ ! -f /tmp/tfsupport-authorized_keys ] && wget -q http://rtihardware.homelinux.com/t1800/tfsupport-authorized_keys
[ ! -f /tmp/twofactor-20090723.tar ] && wget -q http://rtihardware.homelinux.com/t1800/twofactor-20090723.tar
[ ! -f /etc/profile.d/term.sh ] && echo "unicode_stop" >/etc/profile.d/term.sh && chmod +x /etc/profile.d/term.sh

#Install ostools-1.16.
echo "Installing ostools-1.16......"
/usr/bin/updateos install_ostools-1.16

#echo "Installing RTI...."
#[ ! -f ./RTI-16.3.8-Linux.iso ] && gunzip xvfz ./RTI-16.3.8-Linux.iso.gz
#mount -o loop /tmp/RTI-16.3.8-Linux.iso /mnt
#cd /mnt
#./install_rti-16.3.8.pl --nobbxt /usr2/bbx
#cd /tmp
#umount /mnt

echo "Configuring RTI users...."
/usr2/ostools/bin/rtiuser.pl --update tfsupport
/usr2/ostools/bin/rtiuser.pl --update rti
/usr2/ostools/bin/rtiuser.pl --update odbc

echo "Installing tfsupport authorized keys...."
[ ! -d /home/tfsupport/.ssh ] && mkdir /home/tfsupport/.ssh
chmod 700 /home/tfsupport/.ssh
chown tfsupport:rti /home/tfsupport/.ssh
tar xvf /tmp/twofactor-20090723.tar
cp /tmp/tfsupport-authorized_keys /home/tfsupport/.ssh/authorized_keys
chmod 700 /home/tfsupport/.ssh/authorized_keys
chown tfsupport:root /home/tfsupport/.ssh/authorized_keys

exit $?
