#!/bin/bash

#DESC change nic namings from ethX to tfethX

#determine mac address
MACADDR0=`ifconfig eth0 | grep ether | cut -d" " -f10`
if [ "$MACADDR0" != "" ]
then
cat > /etc/udev/rules.d/10-persistent.rules << EOF
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="$MACADDR0", ATTR{type}=="1", KERNEL=="*", NAME="tfeth0"
EOF
fi
MACADDR1=`ifconfig eth1 | grep ether | cut -d" " -f10`
if [ "$MACADDR1" != "" ]
then
cat >> /etc/udev/rules.d/10-persistent.rules << EOF
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="$MACADDR1", ATTR{type}=="1", KERNEL=="*", NAME="tfeth1"
EOF
fi

#add to dracut image
mkdir -p /etc/dracut.conf.d
echo install_items+=\" /etc/udev/rules.d/10-persistent.rules \" > /etc/dracut.conf.d/include-nic-names-rules.conf
dracut -f

#fix ifcfg files
cp -f /etc/sysconfig/network-scripts/ifcfg-eth0 /tmp
sed -i 's/eth0/tfeth0/g' /etc/sysconfig/network-scripts/ifcfg-eth0
mv -f /etc/sysconfig/network-scripts/ifcfg-eth0 /etc/sysconfig/network-scripts/ifcfg-tfeth0
cp -f /etc/sysconfig/network-scripts/ifcfg-eth1 /tmp
sed -i 's/eth1/tfeth1/g' /etc/sysconfig/network-scripts/ifcfg-eth1
mv -f /etc/sysconfig/network-scripts/ifcfg-eth1 /etc/sysconfig/network-scripts/ifcfg-tfeth1

#remove kernel command line ac
cp -f /etc/default/grub /tmp
sed -i 's/net.ifnames=0//g' /etc/default/grub
grub2-mkconfig -o /boot/grub2/grub.cfg
