#!/bin/bash

#DESC Install and configure Relace and Recover.
# determine rsync account.
# install cloud backup.
# cp ssh keys to root account.

# determine rsync cloud server.

# create rear config /etc/rear/local.conf.

GRUB_RESCUE=y
BACKUP=RSYNC
RSYNC_PREFIX="$HOSTNAME"
BACKUP_URL=rsync://tfrsync-${SHOPCODE}@${CLOUDSERVER}:22:/backups/tfrsync-${SHOPCODE}
BACKUP_RSYNC_OPTIONS=( --sparse --archive --hard-links --numeric-ids --stats --acls )

# format usb stick for rear.

# run rear mkrecover.

# run mkbackup.
