#!/bin/bash

# CCE-80841-0
sed -i 's/nullok//g' /etc/pam.d/system-auth

# CCE-80788-3
sed -i '/pam_lastlog/d' /etc/pam.d/postlogin
echo "session required pam_lastlog.so showfailed" >> /etc/pam.d/postlogin

for line in `cat /etc/pam.d/system-auth`
do
[ "`echo $line | grep password`" != "" ] && [ "`echo $line | grep pam_unix.so`" != "" ] && echo "$line remember=5" >>/tmp/system-auth.new || echo $line >>/tmp/system-auth.new
done
cp -f /etc/pam.d/system-auth /tmp
cp -f /tmp/system-auth.new /etc/pam.d/system-auth


