#!/bin/bash

#DESC Harden the system per PCI/PADSS guidelines.
# NOTE: the ostools 1.16 pam config will break the system. do not use. (harden_linux.pl --pam)

/usr2/ostools/bin/harden_linux.pl --ssh
/usr2/ostools/bin/harden_linux.pl --hostsallow
/usr2/ostools/bin/harden_linux.pl --services
/usr2/ostools/bin/harden_linux.pl --logging
/usr2/ostools/bin/harden_linux.pl --logrotate
/usr2/ostools/bin/harden_linux.pl --sudo
/usr2/ostools/bin/harden_linux.pl --ipv6
/usr2/ostools/bin/harden_linux.pl --ids

/usr2/ostools/bin/updateos.pl --samba
/usr2/ostools/bin/updateos.pl --cupsconf
/usr2/ostools/bin/updateos.pl --samba-gen-conf
/usr2/ostools/bin/updateos.pl --samba-set-passdb
/usr2/ostools/bin/updateos.pl --audit-system-configure
/usr2/ostools/bin/updateos.pl --motd

systemctl restart sshd
systemctl restart rsyslog
systemctl restart smb
systemctl restart cups

# Added per insights comliance scan.
# CCE-80841-0
sed -i 's/nullok//g' /etc/pam.d/system-auth

# CCE-80788-3
sed -i '/pam_lastlog/d' /etc/pam.d/postlogin
echo "session required pam_lastlog.so showfailed" >> /etc/pam.d/postlogin
