#!/bin/bash

cd /tmp
wget http://rtihardware.homelinux.com/t1800/RTI-16.1.5-Linux.iso.gz
wget http://rtihardware.homelinux.com/t1800/multiserver.pwd
wget http://rtihardware.homelinux.com/ostools/librxtxSerial.so

echo "Adding multiserver.pwd fix....."
cp -f /tmp/multiserver.pwd /usr2/bbx/config/

echo "Installing 32-bit library for serial ports...."
cp /usr2/basis/lib/librxtxSerial.so /usr2/basis/lib/librxtxSerial.so.64bit
cp librxtxSerial.so /usr2/basis/lib/librxtxSerial.so
chmod 666 /usr2/basis/lib/librxtxSerial.so
chown root:root /usr2/basis/lib/librxtxSerial.so
