#!/bin/bash

#DESC Install TF's CC processing program. (Used by POS software)
cd /usr2/bbx/bin
[ ! -f /usr2/bbx/bin/tcc-latest_linux.tar.gz ] && wget http://rtihardware.homelinux.com/support/tcc/tcc-latest_linux.tar.gz
tar xvfz ./tcc-latest_linux.tar.gz
rm -f ./tcc
rm -f ./tcc_tws
ln -s ./tcc2_rhel7 ./tcc
ln -s ./tcc_rhel7 ./tcc_tws
