#!/bin/bash

cd /tmp
[ ! -f ./apcupsd-3.14.14-18.el8.x86_64.rpm ] && wget http://rhel8repo.centralus.cloudapp.azure.com/ostools-1.17/apcupsd-3.14.14-18.el8.x86_64.rpm
yum -y localinstall ./apcupsd-3.14.14-18.el8.x86_64.rpm
