#!/bin/bash

#DESC Inplace OS upgrade from RH8 to RH9 - RTI.

# clear yum version lock if used
yum versionlock clear

# add leapp package
yum -y install leapp-upgrade

# add leapp repos
cat > /etc/leapp/files/leapp_upgrade_repositories.repo << EOF
[RH8AppStream]
name=RH8AppStream
baseurl=http://rhel8repo.centralus.cloudapp.azure.com/rhel-8-for-x86_64-appstream-rpms

[RH8BaseOS]
name=RH8BaseOS
baseurl=http://rhel8repo.centralus.cloudapp.azure.com/rhel-8-for-x86_64-baseos-rpms

[RH9AppStream]
name=RH9AppStream
baseurl=http://rhel9repo.centralus.cloudapp.azure.com/rhel-9-for-x86_64-appstream-rpms

[RH9BaseOS]
name=RH9BaseOS
baseurl=http://rhel9repo.centralus.cloudapp.azure.com/rhel-9-for-x86_64-baseos-rpms

EOF

#download leapp metadata
cd /etc/leapp/files
wget http://rhel8repo.centralus.cloudapp.azure.com/support/leapp-data17.tar.gz
tar xvfz ./leapp-data17.tar.gz

#remove unneeded kernel drivers
modprobe -r pata_acpi

# run leap upgrade
leapp upgrade --target 9.2 --no-rhsm --reboot
