#!/bin/bash

#DESC Collect "perceptive" data about the system.
#PRDno
#
#HELP Designed to be ran nightly. Produces a summary report in the configured output dir.  
#HELP Decided to do this to investigate scanning results using insights.

#vars
OUTPUT_ROOT_DIR="/usr2/perceptions"
OSMAJORVERS="`cat /etc/redhat-release | cut -d" " -f6 | cut -d. -f1`"

#init
[ ! -d /usr2/perceptions ] && mkdir /usr2/perceptions

#install deps
yum -y openscap yara 

#configure yara malware scanning


#pa-dss compliance openscap scans
oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_pci-dss --results-arf arf.xml --report report.html /usr/share/xml/scap/ssg/content/ssg-rhel${OSMAJORVERSION}-xccdf.xml

#redhat cve info OVAL repo scans


#backup results scans


#available patches scans


#build summary page


exit ?
