#!/bin/bash

#sed -i '/post_install.sh/d' /etc/crontab

# add crontab item to run above script on reboot.
echo "@reboot root /bin/updateos rh8 conf_firewall" >> /etc/crontab
echo "@reboot root /bin/updateos rh8 register_insights" >> /etc/crontab
echo "@reboot root /bin/updateos rh8 zz_email_results" >> /etc/crontab

reboot
