#!/bin/bash

#DESC Creates a systemd service that will run after first reboot only. (After network starts.)
#sed -i '/post_install.sh/d' /etc/crontab
# create post install script
cat > /tmp/post_install.sh <<EOF
#!/bin/bash

/bin/updateos rh8 conf_firewall
/bin/updateos rh8 register_insights
aide -i
cp -f /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
rm -f /etc/yum.repos.d/*
/bin/updateos rh8 rh8repo_install
yum -y reinstall perl
/bin/updateos rh8 install_ostools-1.16
/bin/updateos rh8 install_tcc
update-crypto-policies --set LEGACY
systemctl disable post_install
rm -f /etc/systemd/system/post_install.service
/bin/updateos rh8 zz_email_results
reboot
EOF

# add post install service file to run after network starts.
cat > /etc/systemd/system/post_install.service <<EOF
[Unit]
Description=Post install script for staging.
After=network-online.target

[Service]
Type=idle
ExecStart=/tmp/post_install.sh

[Install]
WantedBy=network-online.target
EOF

chmod +x /tmp/post_install.sh
systemctl enable post_install
