#!/bin/bash

#DESC Enable RTI Real time. (Must have been disabled by updateos rh8 realtime_disable)

# uncomment out jobs.
sed -i 's/^#//g' /usr2/bbx/config/rtiBackgr

# uncomment out cron jobs.
for file in `ls /etc/cron.d`
do 
sed -i 's/^#//g' /etc/cron.d/$file
done

# uncommenting out any jobs in roots crontab
[ -f /var/spool/cron/root ] && sed -i 's/^#//g' /var/spool/cron/root

# uncomment out items in dove.ini
sed -i 's/^#//g' /usr2/bbx/config/dove.ini

# move back doverserver.pl
mv /usr2/bbx/bin/doveserver.pl.bak /usr2/bbx/bin/doveserver.pl

# restore tcc links.
cd /tmp/
find . -name "tcc" -exec mv {} /usr2/bbx/bin \;
find . -name "tcc_tws" -exec mv {} /usr2/bbx/bin \;

# start services
systemctl start blm
systemctl start bbj
systemctl start rti

echo "Real time enabled."

exit 0
