#!/bin/bash

echo -n "Enter hostname: "
read hostname
IP=`ip address | grep inet | grep -v inet6 | grep -v 127.0.0.1 | cut -d" " -f6 | cut -d/ -f1`

[ "$hostname" == "" ] && echo "No hostname provided." && exit 1

hostnamectl set-hostname $hostname
hostnamectl status
sed -i "/$IP/d" /etc/hosts 
echo "$IP          $hostname">>/etc/hosts

exit 0
