#!/bin/bash

useradd tfsupport -g rtiadmin
useradd rti
useradd odbc
useradd delivery

cd /tmp
[ ! -f /tmp/tfsupport-authorized_keys ] && wget http://rtihardware.homelinux.com/t1800/tfsupport-authorized_keys
[ ! -f /tmp/twofactor-20090723.tar ] && wget http://rtihardware.homelinux.com/t1800/twofactor-20090723.tar

echo "Installing tfsupport authorized keys...."
mkdir /home/tfsupport/.ssh
chmod 700 /home/tfsupport/.ssh
chown tfsupport:rti /home/tfsupport/.ssh
tar xvf /tmp/twofactor-20090723.tar
chmod +x /tmp/*.pl
cp /tmp/tfsupport-authorized_keys /home/tfsupport/.ssh/authorized_keys
chmod 700 /home/tfsupport/.ssh/authorized_keys
chown tfsupport:root /home/tfsupport/.ssh/authorized_keys

#echo "Installing admin menus....."
#/tmp/install_adminmenus.pl --run
