#!/bin/bash

cd /tmp
[ ! -f /tmp/RTI-16.1.5-Linux.iso.gz ] && wget http://rtihardware.homelinux.com/t1800/RTI-16.1.5-Linux.iso.gz
[ ! -f /tmp/multiserver.pwd ] && wget http://rtihardware.homelinux.com/t1800/multiserver.pwd
[ ! -f /tmp/librxtxSerial.so ] && wget http://rtihardware.homelinux.com/ostools/librxtxSerial.so

[ ! -f /etc/profile.d/term.sh ] && echo "unicode_stop" >/etc/profile.d/term.sh && chmod +x /etc/profile.d/term.sh

echo "Adding multiserver.pwd fix....."
cp -f /tmp/multiserver.pwd /usr2/bbx/config/

echo "Installing 32-bit library for serial ports...."
cp /usr2/basis/lib/librxtxSerial.so /usr2/basis/lib/librxtxSerial.so.64bit
cp librxtxSerial.so /usr2/basis/lib/librxtxSerial.so
chmod 666 /usr2/basis/lib/librxtxSerial.so
chown root:root /usr2/basis/lib/librxtxSerial.so

echo "Installing RTI...."
[ ! -f ./RTI-16.1.5-Linux.iso ] && gunzip xvfz ./RTI-16.1.5-Linux.iso.gz
mount -o loop /tmp/RTI-16.1.5-Linux.iso /mnt
cd /mnt
./install_rti-16.1.5.pl --nobbxt /usr2/bbx
cd /tmp
umount /mnt
