#!/bin/bash

#sed -i '/post_install.sh/d' /etc/crontab
# create post install script
cat > /tmp/post_install.sh <<EOF
#!/bin/bash

/bin/updateos rh8 conf_firewall
/bin/updateos rh8 register_insights
/bin/updateos rh8 zz_email_results
systemctl disable post_install
rm -f /etc/systemd/system/post_install.service
EOF

# add post install service file to run after network starts.
cat > /etc/systemd/system/post_install.service <<EOF
[Unit]
Description=Post install script for staging.
After=network-online.target

[Service]
Type=idle
ExecStart=/tmp/post_install.sh

[Install]
WantedBy=network-online.target
EOF

chmod +x /tmp/post_install.sh
systemctl enable post_install
reboot
